version: '3.4'
services:
    swoole:
        image: "zaherg/php72-swoole"
        ports:
            - "9501:9501"
        volumes:
            - "./:/var/www"
        command: "php -S 127.0.0.1:8888 -t ."
