version: '3.4'
services:
    swoole:
        image: "twosee/swoole-coroutine"
        ports:
            - "9508:9508"
        volumes:
            - "./:/root/src"
        command: "php -S 127.0.0.1:8888 -t ."
    redis:
        image: redis
        ports:
        - "6379:6379"
        sysctls:
            net.core.somaxconn: 65535
        restart: always

    rabbit:
        image: rabbitmq:3-management
        ports:
          - "5672:5672"
          - "8080:15672"
        environment:
            RABBITMQ_DEFAULT_PASS: password
            RABBITMQ_DEFAULT_USER: user
        restart: always
